name: RailCraft
version: 1.1.4-r1
author: RailRunner16
main: me.railrunner16.railcraft.RailCraft
api-version: 1.13
website: https://railrunner16.me
commands:
  extinguish:
    description: "Extinguish the flames."
    usage: "/extinguish"
    aliases: [ext]
  spawn:
    description: "Teleport to the world spawn."
    usage: "/spawn"
  rtp:
    description: "Teleport into the wild."
    usage: "/rtp"
    aliases: [wild]
  fly:
    description: "Toggle flight."
    usage: "/fly"
  tpa:
    description: "Teleport to another player."
    usage: "/tpa <player>"
  skull:
    description: "Get a player's skull"
    usage: "/skull <player>"
    aliases: [head]
  home:
    description: "Teleport to your home."
    usage: "/home <name>"
  sethome:
    description: "Set a new home."
    usage: "/sethome <name>"
  delhome:
    description: "Delete a home."
    usage: "/delhome <name>"
  enderchest:
    description: "Open your ender chest."
    usage: "/enderchest"
    aliases: [ec]
  workbench:
    description: "Open a crafting table."
    usage: "/workbench"
    aliases: [ct, ctable, craft]
  shovel:
    description: "Spawn a claim shovel."
    usage: "/shovel"
  stack:
    description: "Put your items into stacks."
    usage: "/stack"
  kit:
    description: "Obtain a kit."
    usage: "/kit <name>"
  tpaccept:
    description: "Accept a TPA request"
    usage: "/tpaccept <player>"
  back:
    description: "Go back to your last location"
    usage: "/back"